spring.application.name=fatecads

# Configurações do banco de dados (H2 em memória para desenvolvimento)
spring.datasource.url=jdbc:postgresql://localhost:5432/fatecads_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456

# Atualização automática do esquema do banco de dados
spring.jpa.hibernate.ddl-auto=update

# Mostrar as consultas SQL no console
spring.jpa.show-sql=true

# Não formatar as consultas SQL
spring.jpa.properties.hibernate.format_sql=false

# Console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração da porta do servidor
server.port=8081

# Limite de upload de imagens de produtos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Base publica para gerar links do reset (ex: http://192.168.0.10:8081 ou https://seu-dominio)
# app.base-url=

# Configuracoes de email (reset de senha)
# mail.mode=console | smtp
mail.mode=smtp
mail.from=enzo.stafuza@gmail.com

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=enzo.stafuza@gmail.com
spring.mail.password=fomiqktzoadtxhdw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
