spring.application.name=fatecads

# Configurações do banco de dados (H2 em memória para desenvolvimento)
spring.datasource.url=jdbc:postgresql://localhost:5432/fatecads_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456

# Atualização automática do esquema do banco de dados
spring.jpa.hibernate.ddl-auto=update

# Mostrar as consultas SQL no console
spring.jpa.show-sql=true

# Não formatar as consultas SQL
spring.jpa.properties.hibernate.format_sql=false

# Console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração da porta do servidor
server.port=8081